apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: prd
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: my-container
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
