apiVersion: v1
kind: Namespace
metadata:
  name: prd
kind: Pod
metadata:
  name: my-pod
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: my-container
    image: nginx
#    securityContext:
#      allowPrivilegeEscalation: true
