apiVersion: v1
kind: Namespace
metadata:
  name: prd
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
